### ISSUE TITLE
Seg fault during resizing in CLHT_LB_RES

### ISSUE THREAD

**Issue by prashantpandey** [LPD-EPFL/CLHT#13]
I am seeing a segfault during the resize operation in CLHT_LB_RES. Here's the log and stack trace. 

Any help is much appreciated. 
Thanks!

It seems it is coming from here:
```
279       ssmem_release(clht_alloc, (void*) cur);
```

```
[STATUS-13421772] #bu: 22369622 / #elems: 111384397 / full%: 165.9757% / expands: 22369622 / max expands:  6
[RESIZE-13421772] to #bu 89478488 = MB: 5461.33    | took:   28889809354 ti = 13.757052 s

Thread 10 "main" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffdbbbbe700 (LWP 139857)]
0x000055555555ab6f in ssmem_release ()
(gdb) bt
#0  0x000055555555ab6f in ssmem_release ()
#1  0x0000555555559f70 in clht_gc_release (hashtable=hashtable@entry=0x555555572000)
    at src/clht_gc.c:279
#2  0x00005555555598df in ht_resize_pes (h=h@entry=0x555555571f00, 
    is_increase=is_increase@entry=1, by=<optimized out>) at src/clht_lb_res.c:593
#3  0x00005555555593de in ht_status (h=h@entry=0x555555571f00, 
    resize_increase=resize_increase@entry=1, just_print=just_print@entry=0)
    at src/clht_lb_res.c:707
#4  0x0000555555559771 in clht_put (h=0x555555571f00, key=7536092987517542395, 
    val=<optimized out>) at src/clht_lb_res.c:355
#5  0x0000555555557b56 in do_inserts (id=<optimized out>, keys=0x7fff2888d010, 
    values=0x7ffeaeef3010, start=<optimized out>, n=<optimized out>) at main.cc:32
#6  0x00007ffff7bddde4 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff7ad2609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007ffff79f9293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by trigonak** [comment]
Hello,

I've not seen a similar before. Is it reproducible? Could it be related to the gcc version that you use? Does it happen if you reduce the compiler optimization level?

Vasilis.
